# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-04-17 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haut', '0002_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='image',
            field=models.ImageField(upload_to='staff/'),
        ),
    ]
